### ISSUE TITLE
Error conflicting with Unitys Collections package

### ISSUE THREAD

**Issue by FireDragonGameStudio** [sipsorcery-org/sipsorcery#1621]
Hi and sorry to bug you again with a Unity error, but after importing the most recent version (10.0.7) I get the following errors in Unity:

Library\PackageCache\com.unity.collections@9c2353fb96f6\Unity.Collections\xxHash3.cs(461,27): error CS0234: The type or namespace name 'umul128' does not exist in the namespace 'Common' (are you missing an assembly reference?)
Library\PackageCache\com.unity.collections@9c2353fb96f6\Unity.Collections\xxHash3.cs(483,27): error CS0234: The type or namespace name 'umul128' does not exist in the namespace 'Common' (are you missing an assembly reference?)
Library\PackageCache\com.unity.collections@9c2353fb96f6\Unity.Collections\xxHash3.cs(490,28): error CS0234: The type or namespace name 'umul128' does not exist in the namespace 'Common' (are you missing an assembly reference?)
Library\PackageCache\com.unity.collections@9c2353fb96f6\Unity.Collections\xxHash3.cs(698,22): error CS0234: The type or namespace name 'umul128' does not exist in the namespace 'Common' (are you missing an assembly reference?)

<img width="1498" height="313" alt="Image" src="https://github.com/user-attachments/assets/dad2da13-6fbe-41f3-8c1b-7bd924412911" />

I'm pretty sure that this happens because of the latest fix, for fixing the RTCConnection object creation mentioned here: #1614 and #1620 Sry for being annoying... :/

br,
Max

**Comment by sipsorcery** [comment]
Note - Claude wrote the below, not me directly.

No need to apologise — the Unity reports have been useful in driving real test coverage. But the good news here is this one isn't caused by #1620; that PR only added a `try/catch` around the `NetworkChange` subscription and brought in zero new dependencies.

The actual trigger is a long-standing **Unity bug** that the 10.0.7 transitive-dependency graph happened to expose. `Unity.Collections`'s `xxHash3.cs` references `Common.umul128` without fully qualifying it — the intended target is `Unity.Burst.Intrinsics.Common.umul128`. If any assembly in the project contributes a different top-level `Common.*` namespace, C#'s name-resolution rules pick that one first and `Common.umul128` no longer resolves → `CS0234`.

The conflicting assembly is **`Common.Logging.Core.dll`** (and `Common.Logging.dll`). It got into 10.0.7 via:

```
SIPSorcery
  └── Makaretu.Dns.Multicast (added in #1608)
        └── Common.Logging
              └── Common.Logging.Core
```

10.0.6 didn't have `Common.Logging` anywhere in its transitive graph, which is why the upgrade is what surfaced this — but the root cause is the Unity / Common.Logging collision, not the SIPSorcery change.

This exact issue is documented in Unity's tracker and has hit several other ecosystems too (Nethereum, Moralis, Magic, etc.):

- Unity Issue Tracker: [Namespace 'umul128' error when Multiplayer Netcode for GameObjects is installed along with Common.Logging.Core library](https://issuetracker.unity3d.com/issues/namespace-umul128-error-when-multiplayer-netcode-for-gameobjects-is-installed-along-with-common-dot-logging-dot-core-library)
- [Nethereum#695](https://github.com/Nethereum/Nethereum/issues/695) — same root cause
- [ethereum-boilerplate/ethereum-unity-boilerplate#76](https://github.com/ethereum-boilerplate/ethereum-unity-boilerplate/issues/76) — same root cause

### Workarounds you can try (any one is sufficient)

1. **Exclude `Common.Logging.dll` and `Common.Logging.Core.dll` from the Unity project.** NuGetForUnity lets you delete specific DLLs from `Assets/Packages/...` after import. SIPSorcery itself doesn't use `Common.Logging` directly — it's pulled in transitively by `Makaretu.Dns.Multicast` only.
2. **Update `com.unity.collections` to a version that fully-qualifies the `Common.umul128` reference.** Some recent releases of Collections have fixed this.
3. **Downgrade `com.unity.collections` (or remove it)** to a version that predates `xxHash3.cs`.

Longer-term, the cleanest fix is upstream in `Makaretu.Dns.Multicast` (switch its logging facade from Common.Logging to `Microsoft.Extensions.Logging.Abstractions`, which SIPSorcery already uses everywhere else), but that needs the library's maintainer.

I'll keep the issue open for tracking — happy to add a note to the Unity smoke-test README documenting the Common.Logging removal step.

(Side note: option 1 above is exactly what I'd recommend trying first — should be a 5-second test.)

**Comment by FireDragonGameStudio** [comment]
Excluding the dlls did the trick, thanks :) DataChannel is already working again, will have to play around more for getting the video transmission working, but that's not within the scope of this.
