### ISSUE TITLE
Xamarin Sample - XamarinDataChannelTest error with Sorcery 5.2.3

### ISSUE THREAD

**Issue by matteopiccioni** [sipsorcery-org/sipsorcery#586]
When compiling I have
```
- Error CS1061: 'Task<RTCDataChannel>' does not contain a definition for 'onDatamessage' and no accessible extension method 'onDatamessage' accepting a first argument of type 'Task<RTCDataChannel>' could be found (are you missing a using directive or an assembly reference?) (CS1061) (XamarinDataChannelTest)

- Error CS1061: 'Task<RTCDataChannel>' does not contain a definition for 'onmessage' and no accessible extension method 'onmessage' accepting a first argument of type 'Task<RTCDataChannel>' could be found (are you missing a using directive or an assembly reference?) (CS1061) (XamarinDataChannelTest)

- Error CS1503: Argument 2: cannot convert from 'System.Threading.Tasks.Task<SIPSorcery.Net.RTCDataChannel>' to 'SIPSorcery.Net.RTCDataChannel' (CS1503) (XamarinDataChannelTest)

- Error CS1061: 'RTCDataChannel' does not contain a definition for 'sendAsync' and no accessible extension method 'sendAsync' accepting a first argument of type 'RTCDataChannel' could be found (are you missing a using directive or an assembly reference?) (CS1061) (XamarinDataChannelTest)
```

It works with Sorcery 5.1.0

Thanks
